version: '3.1'

services:
  postgres_db:
    image: postgres:latest
    env_file:
      - local_environ.env
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}