version: '3.1'

services:
  postgres_db:
    image: postgres:latest
    env_file:
      - local_environ.env
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=librarydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123